"""
Critic node for the LangGraph application.

This node evaluates and critiques suggestions generated by the suggestion node.
"""

from .state import GraphState


def critic_node(state: GraphState) -> GraphState:
    """
    Node that critiques/evaluates the suggestion.
    
    This node takes the current state, reads the suggestion,
    and generates a critique or evaluation of that suggestion.
    
    Args:
        state: The current graph state (should contain a 'suggestion' field)
        
    Returns:
        Updated state with 'critique' and 'response' fields populated
    """
    # Get the suggestion from state
    suggestion = state.get("suggestion", "")
    
    # Generate a critique based on the suggestion
    if suggestion:
        critique = f"Critique: The suggestion '{suggestion}' has merit. However, consider the implementation complexity and resource requirements. It would be beneficial to validate user demand before full implementation."
    else:
        critique = "Critique: No suggestion found in state to evaluate."
    
    # Return updated state with both critique and response
    # (response is the output field for the API, critique is for internal use)
    return {
        "critique": critique,
        "response": critique  # Both fields have the same value
    }

