"""
State schema definition for the LangGraph application.
"""

from typing import TypedDict
from typing_extensions import NotRequired


class GraphState(TypedDict):
    """
    State schema for the LangGraph application.
    
    This state is passed between nodes and contains:
    - userInput: User's input text
    - messages: Conversation history with role and content
    - pdf: PDF document information (type and data)
    - interviewSummary: Summary from interview node analysis
    - guardrailsStatus: Status message from guardrails check
    - guardrailsSafe: Boolean indicating if content passed safety checks
    - suggestion: The suggestion generated by the suggestion node
    - critique: The critique/evaluation provided by the critic node
    - response: The final response (critique)
    - finalSuggestion: The final suggestion output
    
    Biohacker-specific fields:
    - userProfile: User demographic data (age, gender, job)
    - bloodData: Dictionary of biomarker names to values
    - selectedIntervention: The chosen intervention from the database
    - challenge: 10-day challenge routine for user engagement
    - scientificReferences: References supporting the recommendation
    - problematicBiomarkers: List of biomarkers needing attention
    """
    userInput: NotRequired[str]  # User's input text
    messages: NotRequired[list]  # List of message dicts with role/content
    pdf: NotRequired[dict]  # PDF info with type and data fields
    interviewSummary: NotRequired[str]  # Generated by interview node
    guardrailsStatus: NotRequired[str]  # Generated by guardrails node
    guardrailsSafe: NotRequired[bool]  # Safety check result
    suggestion: NotRequired[str]  # Generated by suggestion node
    critique: NotRequired[str]  # Generated by critic node
    response: NotRequired[str]  # Final response (critique)
    finalSuggestion: NotRequired[bool]  # Boolean indicating if suggestion is approved
    
    # Biohacker fields
    userProfile: NotRequired[dict]  # {age: int, gender: str, job: str, height_cm: float, weight_kg: float, sleep_hours_per_night: float, movement_days_per_week: int, work_activity_level: str, stress_level_1_to_10: int}
    bloodData: NotRequired[dict]  # {biomarker_name: value}
    smartwatchData: NotRequired[dict]  # {hrv, vo2_max, resting_heart_rate, active_minutes, sleep_stages}
    selectedIntervention: NotRequired[dict]  # Intervention from database
    challenge: NotRequired[dict]  # 10-day challenge routine
    scientificReferences: NotRequired[list]  # List of references
    problematicBiomarkers: NotRequired[list]  # Markers needing attention

