"""
State schema definition for the LangGraph application.
"""

from typing import TypedDict
from typing_extensions import NotRequired


class GraphState(TypedDict):
    """
    State schema for the LangGraph application.
    
    This state is passed between nodes and contains:
    - userInput: User's input text
    - messages: Conversation history with role and content
    - pdf: PDF document information (type and data)
    - interviewSummary: Summary from interview node analysis
    - guardrailsStatus: Status message from guardrails check
    - guardrailsSafe: Boolean indicating if content passed safety checks
    - suggestion: The suggestion generated by the suggestion node
    - critique: The critique/evaluation provided by the critic node
    - response: The final response (critique)
    - finalSuggestion: The final suggestion output
    """
    userInput: NotRequired[str]  # User's input text
    messages: NotRequired[list]  # List of message dicts with role/content
    pdf: NotRequired[dict]  # PDF info with type and data fields
    interviewSummary: NotRequired[str]  # Generated by interview node
    guardrailsStatus: NotRequired[str]  # Generated by guardrails node
    guardrailsSafe: NotRequired[bool]  # Safety check result
    suggestion: NotRequired[str]  # Generated by suggestion node
    critique: NotRequired[str]  # Generated by critic node
    response: NotRequired[str]  # Final response (critique)
    finalSuggestion: NotRequired[str]  # Final suggestion output

